name: Nightly Release

on:
  schedule:
    - cron: '45 9 * * *' # 9.45 AM UTC everyday 

jobs:
  nightly_build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        ref: 'dev'
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name : Install Prerequisites
      run : |
        sudo apt-get install gcc libpq-dev -y
        sudo apt-get install python-dev  python-pip -y
        sudo apt-get install python3-dev python3-pip python3-venv python3-wheel -y
        pip3 install wheel
    - name : Update Version numbers
      run : |
        python .github/prepare-nightly.py
    - name: Build sdist and bdist_wheel
      run: python setup.py sdist bdist_wheel
    - name: Publish distribution ðŸ“¦ to Test PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.test_pypi_password }}
        skip_existing: true
        repository_url: https://test.pypi.org/legacy/
    - name: Publish distribution ðŸ“¦ to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.pypi_password }}
        skip_existing: true